### ISSUE TITLE
Missing phyllum Porifera

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#155]
@olafbanki @mdoering 
I think we have a big problem with CoL in the Clearinghouse.

Today we discovered that entire phyllum Porifera disappeared in assembly tree:

![image](https://user-images.githubusercontent.com/28574252/86972254-451bca80-c138-11ea-86b5-848426489a2c.png)

How it might be happened?!

It was in a place in CoL 2020-06-04 Beta (still not deployed!):

![image](https://user-images.githubusercontent.com/28574252/86972392-80b69480-c138-11ea-8a99-0b85c2ba1b0f.png)

What else might be missing in CoL?

**Comment by mdoering** [comment]
You mean this one?
https://data.catalogue.life/catalogue/3/taxon/0a1cb16d-2ca4-46dd-9fa8-92ec5c9ea77d

<img width="1799" alt="Screenshot 2020-07-09 at 13 27 25" src="https://user-images.githubusercontent.com/327505/87034350-f7f73180-c1e7-11ea-9296-b6de9615a0c6.png">

Looks like you synced all sectors? There are over 2700 new syncs since last deploy:
https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0

 In which case some taxa get temporarily moved elsewhere during syncs, that might have happened when you looked.
