### ISSUE TITLE
Remove redundant ITIS datasets

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#160]
There are 5 ITIS datasets registered now: https://data.catalogue.life/dataset?limit=50&offset=0&q=itis

can we just keep 3 ITIS datasets: 
 - ITIS Bees (ACEF)
 - ITIS Global (ACEF)
 - ITIS as the new ColDP based one

There seems to be 3 full ITIS datasets of them now:
 - [2028](https://data.catalogue.life/dataset/2028/imports): DwCA from GBIF 597120 taxa
 - [2120](https://data.catalogue.life/dataset/2120/imports): managed 600175 taxa
 - [2144](https://data.catalogue.life/dataset/2144/imports): 600536 taxa

Once we migrated CoL to use the new full dataset we should also delete the Bees and Global dataset

**Comment by gdower** [comment]
This is a known issue that @yroskov and I already are working on, and the old ITIS datasets will be replaced and removed gradually as the new ITIS dataset is assembled. I'll put it on the next annual edition project board.

Large datasets like ITIS often are going to have 2 versions in the Clearinghouse while the new dataset is being assembled, because it will likely take more than 1 monthly release to handle the assembly.

**Comment by gdower** [comment]
There probably still will be 2 ITIS datasets when this process is complete with the CoLDP ITIS and DwCA from GBIF.

**Comment by yroskov** [comment]
@gdower We can already remove ITIS Bees [1067] from ClearingH

**Comment by mdoering** [comment]
@gdower there is no need to still have the GBIF DwCA one if we get a complete and more modern ColDP version.

Once we can remove the DwCA ITIS dataset we just have to make sure to copy the GBIF registry key to the ColDP version so the DwC one does not show up again when syncing with the registry. And to turn on the `Gbif Sync Lock` setting to avoid it gets overwritten again with older GBIF metadata. 

Or you keep the GBIF dataset, replace its data with the ColDP archive and turn on the `Gbif Sync Lock`.

**Comment by yroskov** [comment]
Just a reminder: by mistake I have assembled 59 sectors from ITIS-DwCA [2028] and 6 sectors from ITIS-ColDP [2144]. Geoff scheduled "rescue" job for Monday.

**Comment by gdower** [comment]
> @gdower there is no need to still have the GBIF DwCA one if we get a complete and more modern ColDP version.
> 
> Once we can remove the DwCA ITIS dataset we just have to make sure to copy the GBIF registry key to the ColDP version so the DwC one does not show up again when syncing with the registry. And to turn on the `Gbif Sync Lock` setting to avoid it gets overwritten again with older GBIF metadata.
> 
> Or you keep the GBIF dataset, replace its data with the ColDP archive and turn on the `Gbif Sync Lock`.

I really dislike the idea of putting the GBIF key in the CoLDP archive because it implies that they are the same. The CoLDP version is almost certainly going to be different from the GBIF DwC version and it will create confusion suggesting that they are the same dataset in the metadata. If we cannot block the dataset from syncing into the Clearinghouse from GBIF, then I think it is better to just keep the duplicate in the clearinghouse, because they are 2 distinct versions of the ITIS dataset. If people search for ITIS in the clearinghouse, they will see both datasets and can pick which one they want to use after viewing the metadata. I don't want someone to waste a bunch of their time trying to figure out why the CoL Clearinghouse CoLDP version of ITIS does not match the dataset on gbif.org.

**Comment by mdoering** [comment]
In GBIF there is the clear policy never to have different versions of the same dataset around. I very much like that and think the version registered at GBIF should really be replaced by the newer ColDP one. Unfortunately we cannot (yet) register ColDP datasets in GBIF. So the only way to do it is to delete the DwC one, copy the GBIF key to the ColDP version and deactive the GBIF registry sync. Can you go to ITIS and select two different views? There is only one and we should make sure for every dataset there is only a single public copy. I don't mind other private working copies.

And yes I agree, having the GBIF key in there implies they are the same. But thats what they are. Different views, both in time and format, of the same dataset.

If I am not mistaken @dhobern and some other people are working on setting up guidelines and best practices for datasets in the Clearinghouse. I strongly believe this should be one of them. Having multiple release datasets of a project like CoL in the Clearinghouse is different in that these are clearly marked as immutable editions of a single project.

**Comment by mdoering** [comment]
Some more reasons why we must make sure dataset keys do not change. Changing the dataset key for a dataset causes many problems:

 - import history is lost
 - historic dataset metrics are lost
 - sector sync history is lost
 - historic sector metrics are lost
 - dataset links and citations break
 - (near future) dataset DOI will be broken as the primary way how to cite datasets
 - global record identifiers are broken as they are composite keys made of DATASET_KEY : TAXON_ID

There should strictly be only one public dataset copy for every dataset with a stable datasetKey!
It is ok to have further _private_ copies if needed for tests. But these must be _private_ and should not be used in the main CoL project for real sectors.

Stable dataset keys are probably even more important than name/record ids in the Catalogue of Life.

**Comment by yroskov** [comment]
I can only support your statement: **dataset keys should never be changed**. It was the rule in CoL through its 19 years. Every unique database kept persistent ID, even if its title evolved through the time. Damm, IDs changed when our resources migrated in the Clearinghouse!! and all items from your list will be lost.

We need to adopt Clearinghouse to the process of CoL assembly. At the moment, we have serious problems with managing updates through different data submission formats, different database "views" and often cannot control metadata in the Clearinghouse. I relies on @gdower for improvements, because he understand both sides of the process.

**Comment by mdoering** [comment]
Can we clear up ITIS datasets for the go live in december please?
https://data.catalogue.life/dataset?limit=50&offset=0&q=itis

Please make the ones private which are for tests only and update the titles to better reflect their purpose. E.g. ITIS Global or Bees being an export of ITIS as in COL 2018. Maybe we can even completely remove those now?

**Comment by mdoering** [comment]
Looks like there is just one ITIS in use currently by COL - lets remove all others then!
