### ISSUE TITLE
MilliBase - missing synonym - genus Yamasinaium 

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#252]
**Describe the problem**:

From the GBIF Portal feedback: https://github.com/gbif/portal-feedback/issues/3305
I am tagging @RyoKuwa who originally reported the issue.

**Genus Yamashinaium is synonym with Yamasinaium**

Takakuwa (1954) mistakenly introduced Yamasinaium as "Yamashinaium" and Yamasinaium noduligerum as "Yamashinaium noduligerum".

**Link to effected CoL webpages**:
I couldn't find the page for the genus so here is for the species I found: https://www.catalogueoflife.org/data/taxon/58M67

**Literature references**:
Takakuwa, Y. (1954) The Diplopods of Japan and Adjacent Areas. Japan Society for the Promotion of Science, Tokyo. (In Japanese with some description in German).

**Comment by yroskov** [comment]
@bart-v, would it be for WoRMS authors?

**Comment by mdoering** [comment]
It was actually wrong in the 2020-12 version of COL and WoRMS we used then:
https://data.catalogueoflife.org/dataset/2242/taxon/5CQY5

And as you can see even in the current version of Millibase there are 2 bare names, i.e. names not linked to any synonym or taxon:

https://data.catalogueoflife.org/dataset/1200/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Yamashinaium&sortBy=taxonomic

These dont cause problems as we do not use bare names when assembling the COL Checklist. But they probably are in the system because they had been a taxon at some point?

Anyways, the problem appears to be gone now.
