### ISSUE TITLE
ITIS - potentially incorrect synonym - Geomys bursarius llanensis and Geomys texensis llanensis

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#265]
**Describe the problem**:
Issue originally reported on the GBIF Feedback portal (https://github.com/gbif/portal-feedback/issues/2824) by @rspfau

According to the feedback message, Geomys bursarius llanensis and Geomys texensis llanensis shouldn't be synonyms.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/5HFV4
https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=900270#null

**Literature references**:
None.

**Comment by yroskov** [comment]
@DaveNicolson, what do you think?

**Comment by DaveNicolson** [comment]
I can look into this next week (I am out of town now), but the language suggests that the issues is not with the relationship between the names, but rather with the application of particular names to particular specimens. That is a matter for specimen collections & GBIF, if my initial impression is correct. It is hard to argue that two different combinations of the same 'basionym' should not be synonymous in a nomenclatural sense. Am I missing something? -Dave

**Comment by DaveNicolson** [comment]
Sorry that I didn't come back to this after my travel. In any case, the issue from GBIF on this has to do with the names applied to specimens, not with the taxonomy _per se_.

 E.g., "There have been several taxonomic changes over the years since Bailey gave this name in 1905, but some specimens are incorrect. For example: https://www.gbif.org/occurrence/583463275. This is definitely Geomys bursarius and not G. texensis. The museum where this specimen is housed has the name correct, but it's changed to G. texensis here on GBIF"

Unless someone can find an issue buried in this that has to do with the taxonomic arrangement in ITIS, this is not an issue for ITIS, but rather for the occurrence/specimen records in GBIF. Like I said, am I missing something? -Dave

**Comment by mdoering** [comment]
I agree with @DaveNicolson that there is no reason given that the taxonomy is incorrect. In fact just by looking at the 2 subspecies they obviously are homotypic so they should be synonyms: https://www.catalogueoflife.org/data/taxon/5HFV4

> Geomys texensis llanensis Bailey, 1905
> = Geomys bursarius llanensis Bailey, 1905
> = Geomys breviceps llanensis Bailey, 1905

If there is no further evidence given this is just noise.

**Comment by mdoering** [comment]
@ManonGros I think before we move any issue to COL we should make sure that there is evidence of sth being at least potentially wrong. There should be a reference to proof, just saying sth is wrong is not good enough in my opinion. I would even suggest to close such issues on [gbif-feedback](http://github.com/gbif/portal-feedback/issues/).

**Comment by ManonGros** [comment]
Thanks @mdoering, we will try to be more thorough next time!

We try to check the issues before forwarding them but we are not always able to determine the legitimate issues from opinions and misconceptions. Sometimes the users don't provide references but it doesn't mean that the claim is unsupported (and I don't always know where to check).
