### ISSUE TITLE
3i Auchenorrhyncha - possibly incorrect synonym - Tettigonia cantans

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#396]
**Describe the problem**:
Based on a message originally logged in the GBIF Feedback portal: https://github.com/gbif/portal-feedback/issues/3868

According to this user, Tettigonia cantans (https://en.wikipedia.org/wiki/Tettigonia_cantans) and Euryphara cantans shouldn't be synonyms. They belong to different families and have different distributions.

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3D5VX

**Literature references**:
No reference provided other than the wikipedia page for Tettigonia cantans (https://en.wikipedia.org/wiki/Tettigonia_cantans)

**Comment by mdoering** [comment]
Tettigonia cantans is listed in [OSF](http://orthoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1142803) and a common species in Europe: http://www.orthoptera.ch/arten/item/tettigonia-cantans

**Comment by yroskov** [comment]
@proceps, for your information

**Comment by proceps** [comment]
Tettigonia cantans Fabricius, 1794 is the original combination of Euryphara cantans (Fabricius, 1794) (fam. Cicadidae);
Tettigonia cantans (Fuessly, 1775) with the original combination Gryllus cantans Fuessly, 1775 (fam. Tettigoniidae).

Two names are not synonyms, at cirtain period of time the two probably were secondary homonyms, but they are classified in different genera know. Please note the author string.

I repeated this many time, the problem of Catologue of Life is treat the original combinations in zoology are treated as "synonyms" in the CoL and GBIF. They are not. This is only the source of confusion for users.

**Comment by mdoering** [comment]
Thanks @proceps, I overlooked the author difference. Guess I did not notice it as both start with an F.

They are both in COL & GBIF:
https://www.catalogueoflife.org/data/search?q=Tettigonia%20cantans
https://www.gbif.org/species/search?q=Tettigonia%20cantans

I still don't see the problem with the original combination being treated as a _Synonyms and Combinations_. Clearly you can encounter records of [Tettigonia cantans Fabricius, 1794](https://www.gbif.org/occurrence/search?taxon_key=1692881) which need to be interpreted correctly as Euryphara instead of Tettigonia. And knowing the original combination like any other _synonym_ is important for that.
