### ISSUE TITLE
Index of Mosses Database (W³MOST)

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#402]
The moss registration system for ICN:
http://www.mobot.org/mobot/tropicos/most/iom.shtml

COL already includes MOST for the moss taxonomy, but it is heavily outdated and based on data from 2004:
https://www.catalogueoflife.org/data/dataset/1019

**Comment by mdoering** [comment]
@dhobern should we reach out to Tropicos? We had been in contact before and 18 years of no updates is pretty serious.

**Comment by dhobern** [comment]
Good idea. I'll forward to Chantal so we don't forget.

**Comment by chantalhuijbers** [comment]
I have been in touch with them during the data license consultation process. The contact person is now John Brinda.
He wrote (16 June 2021):
Marshall Crosby has been retired for quite some time now. The moss checklist was essentially abandoned for a few years, but I have been working on reviving it with input from Marshall and several other people. I think you might as well just put me down as the new contact person for this dataset since I can probably answer most questions anyone might have about it.

The new version of the bryophyte checklist I am working on will be incorporated into the WFO backbone and we are also starting to use it for the bryophyte portal <https://bryophyteportal.org/>. In addition, I am beta-testing a separate website for exploring it at: <https://www.bryonames.org/>

@dhobern How do we want to move forward with this?

**Comment by olafbanki** [comment]
Bryonames was added to the COL Checklist in December 2022 replacing W3MOST https://www.checklistbank.org/dataset/9854/about
