### ISSUE TITLE
ReptileDB name with missing authorship bracket

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#41]
https://dev.col.plus/dataset/1008/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=unmatched%20name%20brackets&limit=100

e.g.
 - Mabuya sulcata (Peters, 1867
 - Ameivula mumbuca (Colli, Caldwell, Costa, Gainsbury, Garda, Mesquita, Filho, Soares, Silva, Valdujo, Vieira, Vitt,

**Comment by gdower** [comment]
@mdoering, we probably need to fix minor issues like these by reporting them to the GSD with the review queues. If we fix minor issues like this on our end and it isn't corrected in the GSD, it will just get overwritten on the next update, unless it is a remembered decision by CoL+.

The 2nd issue might be field truncation by the old infrastructure, and those truncation issues will be resolved as we process updates. ReptileDB does have an update, which we'll probably try to get to as soon as possible after the first CoL+ monthly edition.

**Comment by mdoering** [comment]
If it indeed is like this in the source then sure, it makes no sense to correct them on our end.
Is it worth collecting these issue in github for each dataset so you can address them once you engage with them? The planned feedback queue will take a while to establish

**Comment by gdower** [comment]
@mdoering, keeping track of these issues is useful, although isn't this already going to get caught by the [unmatched brackets](https://www.col.plus/dataset/1008/issues) issues? We could email that link to the GSDs when we are working with them on updates, highlighting the particular ones that are due to mistakes in the data. @yroskov and I discussed design of the issues queue for fine-tuning it so that we can send it to GSDs as a temporary review queue. I'll open a frontend design ticket on that discussion.

After we get the first CoL+ monthly edition released, I have an idea on how we can potentially tackle fixing these small typos:

We need the capability to edit and remember edits, because not all GSDs will have the time and resources to fix large numbers of small typos. Meanwhile, we get complaints about typos from CoL+ and GBIF users. I'm not opposed to the idea of fixing these issues on our end, but not if the changes will get overwritten each time a dataset is updated. I have an idea on how we could remember decisions and apply them as pre-processing to the data before importing them into CoL+ with the patches also posted in the GitHub repos. The same algorithm could eventually be implemented in CoL+ and the importer would apply the stored data patches from the GitHub repo. After we get the first monthly release out, let's talk more about this.

**Comment by mdoering** [comment]
We do have the option to apply a name and authorship correction with a decision already:

<img width="1328" alt="Screenshot 2019-08-22 at 22 45 06" src="https://user-images.githubusercontent.com/327505/63548450-89a57400-c52e-11e9-8856-4f7bb374829f.png">

See also https://github.com/Sp2000/colplus-frontend/issues/313

**Comment by camiplata** [comment]
This is not longer an issue, probably was fixed already in 2019
