### ISSUE TITLE
Scientific names of nothospecies malformed, reopened

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#448]
In #431, I reported about extra spaces in scientific names of nothospecies.
Almost all of them are fixed in the Jun 2022 edition of CoL.
However, the following 13 nothospecies in World Plants still have an extra space in the name:

Carya ×  brownii
Carya ×  collina
Carya ×  demareei
Carya ×  dunbarii
Carya ×  laneyi
Carya ×  lecontei
Carya ×  ludoviciana
Carya ×  nussbaumeri
Carya ×  schneckii
Juglans ×  avellana
Juglans ×  intermedia
Juglans ×  notha
Myrica ×  ujhanovii

**Comment by mdoering** [comment]
@yroskov please check if thats the case also in the source dataset and when that was last imported. If older it might just need to be reimported

**Comment by mdoering** [comment]
The World Plants source data looks fine:
https://api.checklistbank.org/dataset/1141/taxon/Fagales-Juglandaceae-Juglandoideae-Carya-×%20brownii-Sarg.
https://www.checklistbank.org/dataset/1141/taxon/Fagales-Juglandaceae-Juglandoideae-Carya-×%20brownii-Sarg.

The same name in COL June 2022 is fine, but the speciesEpithet field has indeed a leading space which is wrong:
https://api.checklistbank.org/dataset/9828/taxon/RHTD

This has been fixed in the latest July edition!
https://api.checklistbank.org/dataset/9830/taxon/RHTD

I would consider this solved. @aoern or can you point me to the place where it still occurs?

**Comment by aoern** [comment]
Fine!
I'll reverify the published July edition when available and report the results here.

**Comment by aoern** [comment]
Verified in July version. No extra spaces any more.
