### ISSUE TITLE
Phylum Onychophora

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#468]
Phylum [Onychophora](https://www.catalogueoflife.org/data/taxon/99CY3) has 2 synonyms which are spelled wrongly.
It should be "chophora" not "cophora"

https://www.gbif.org/species/182598826
https://en.wikipedia.org/wiki/Euonychophora

There are also no classes in this phylum. Maybe follow [Myriatrix](https://www.gbif.org/species/182598786)?

**Comment by DaveNicolson** [comment]
I am doubly-confused. First it was noted that ITIS' Onychophora were out of date (which was fair), so we provided a full update of the group at the end of June this year.

Now there is a perceived issue with the spelling of 2 names in synonymy (at the top level) and the lack of classes in the group (which has gone back and forth over the last couple decades) and it is suggested to follow Myriatrix. If you want to follow Myriatrix I guess that's OK. But as to the lack of classes, that is explained in the ITIS records in ITIS with these comments:
"Although Ruggiero et al. (2015) used class Udeonycophora and order Euonycophora, more recent works (Brusca et al. 2016, Giribet & Edgecombe 2020) place the two families directly under Onychophora"

I do not have a more detailed explanation for the stance for (or against) using classes in Onychophora, but we have not seen a solid resolution of this (ongoing) dispute. The source ITIS followed (which Myriatrix also follows) does not mention any names above family rank (other than Onychophora):
http://www.onychophora.com/list.htm

I do not know why Myriatrix has chosen to retain ranked names between Onychophora and the families. Perhaps they know something we did not know when updating ITIS.

As to the spellings, the classification from Ruggiero et al. (2015, & corrected 2015) spelled those names as shown in ITIS:
Phylum Onychophora
..Class Udeonycophora
....Order Euonycophora

Perhaps those names were spelled wrongly in that work. It sure looks like that is the case, but if so, the misspelled names do still belong in ITIS since they are literature-based misspellings. So the ideal solution for ITIS would be to add the correctly-spelled names in synonymy, as well.

A paper from 2000 proposed a a classification for extant and fossil/extinct that added multiple levels, especially to accomodate the non-extant taxa. Looking _only_ at extant taxa, the classiciation would simplify to this:
Subphylum Onychophora GRUBE 1853 
.Class Udeonychophora n.mom. 
..Order Euonychophora HUTCHINSON 1930 
...Family Peripatidae EVANS 1901 
...Family Peripatopsidae BOUVIER 1904, 1907

BUT Oliviera et al. (2012) world checklist also did not use names between family & Onychophora:
https://zookeys.pensoft.net/articles.php?id=2951

It is worth noting that the management hierarchy Ruggiero was producing up until the end of 2019 did not end up using names between Onychophora and the families, and included this comment (with my square-bracketed notes): "includes Udeonycophora [sic] & Euonycophora [sic] (syns.) per Brusca 2018  pers. comm."

For now, we will have a look at adding the correctly-spelled names in synonymy under Onychophora in ITIS, so at least they will be visible in COL etc.

**Comment by mdoering** [comment]
Sorry for the confusion Dave. And much appreciated your detailed response. I have not been part of that previous discussion, so I wasnt aware. It all makes sense. I would probably only add the 2 extra spellings to the synonymy :)

**Comment by mdoering** [comment]
@olafbanki @dhobern I guess this shows again how difficult it is to understand the existing decisions in COL from the outside. We need to capture those works and discussions that form the basis for decisions of the COL hierarchy in particular.

**Comment by DaveNicolson** [comment]
I've just gotten an update file that adds the correctly-spelled names in synonymy. It is too late for this month's load, which we are in the process of finalizing, so it will be included in the ITIS load at the end of October.

**Comment by DaveNicolson** [comment]
Out of curiosity, when you refer to decisions of the COL hierarchy, does that mean anything above family, or anything above a GSD, or... ? Thanks!

**Comment by mdoering** [comment]
Good question. As a user I guess it doesnt really matter if it's the core COL hierarchy outside a GSD or inside a GSD. I simply want to understand why a group is treated that way. Not sure how thats best documented. Listing consulted publications that are being followed like you have in ITIS are a large step towards that transparency I suppose. But sometimes there is more discussion and decisions being taken which are based on several, sometimes contradicting, works.

**Comment by DaveNicolson** [comment]
This issues was addressed in ITIS a while back, and the group was updated again in 12/2023, so I think this issue can be closed?
