### ISSUE TITLE
Mangled distributions from WoRMS

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/data#483]
See the distributions here: https://www.catalogueoflife.org/data/taxon/5W2WT

mrgid:marineregions.org , mrgid:mrgid , mrgid:48182 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48140 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48142 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48151 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48214 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48213 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48115 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48122 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48457 , mrgid:marineregions.org , mrgid:mrgid , mrgid:48366

This seems to be a set of triples with subjects, predicates and objects all concatenated as a single comma-separated string - we should work with WoRMS to get these flowing through in a better format and probably just as the objects (country names or ISO codes should be plausible in this case, but at very least URIs like http://marineregions.org/mrgid/48182, etc.).

**Comment by yroskov** [comment]
Dear @bart-v (@gdower) could you please have look on this?

**Comment by mdoering** [comment]
The [ColDP distributions](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#distribution) should consist of an identifier `areaID` and a controlled `gazetteer` value to know the context and optionally a human label `area`. See discussion at https://github.com/CatalogueOfLife/coldp/issues/40. The ColDP docs don't seem to line up, I'll update them.

For example in the case above one record with:

```
gazetteer=mrgid
areaID=48142 
```

The currently provided values from WoRMS are not that far off, they just use URLs for areaID which appears be the problem here. It is interpreted as a concatenation of multiple values:

https://www.checklistbank.org/dataset/1130/verbatim/308476

```
col:area = Ireland
col:areaID = http://marineregions.org/mrgid/48213
col:taxonID = urn:lsid:marinespecies.org:taxname:875546
col:gazetteer = mrgid
```

**Comment by mdoering** [comment]
@bart-v the distribution looks fine to me, I'll make sure we interpret the URL value as a single value.
Showing the area name is a bit more difficult though - we will need to track the entire MRGID enumeration in the backend like we do for TDWG, ISO and other codes.

**Comment by mdoering** [comment]
@bart-v looking at MRGID it appears it actually refers to other standards like TDWG in this case:
https://marineregions.org/gazetteer.php?p=details&id=48213

Relations:
Part of	  [Ireland](https://marineregions.org/gazetteer.php?p=details&id=47660) (TDWG - level 3)	 
Has preferred alternative	  [Ireland](https://marineregions.org/gazetteer.php?p=details&id=2114) (Nation)	  [[view hierarchy](https://marineregions.org/gazetteer.php?p=browser&id=62958#focus)]

Is MRGID not a standard on its own but rather a managed collection of other standards as linked data for placenames? I am confused that there is a preferred alternative given.

**Comment by mdoering** [comment]
Reopening as the issue is adressed in the backend code, but not in the data. Potentially all WoRMS sources should be reimported and resynced now.

**Comment by bart-v** [comment]
This issue has been there for quite a while, but I always assume what we send is just OK.
Great to see that confirmed & thanks for looking into this now.

MarineRegions (MRGID) is indeed a mixture of multiple existing standards and a multitude of entries that are not part of any other standard at all: obviously and especially marine place names.

The "preferred alternative" is just there to indicate the preferred MRGID within the standard, not a link to an external standard.

Thus, I think COL should consider this as a separate standard, especially since we assign proper PIDs to it.

**Comment by mdoering** [comment]
Thanks @bart-v, could you explain a little more how MarineRegions works? If I understand correctly it is assembled from all these sources here: https://marineregions.org/sources.php

When/how often does it change? Are their distinct releases with versions? I can only seem to be able to [download](https://marineregions.org/downloads.php) individual sources, but not the entire MarineRegions. Is it available somewhere e.g. to lookup a region name from an MRGID?

**Comment by bart-v** [comment]
The system is updated constantly, just like WoRMS.

We have multiple ways to access the data, i.e. a Linked Data Event Streams (LDES) feed
https://www.marineregions.org/gazetteer.php?p=webservices

**Comment by mdoering** [comment]
Great. To seed a system before using LDES you would use REST or does LDES provide you with simple ways to access a "snapshot"? I havent used LDES before, looks useful.
