### ISSUE TITLE
Problems with zoological rank 'section'

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#571]
Botanical rank section is a commonly used infrageneric rank, while zoological rank section is a rarely used rank (about 20 cases in CoL) between order group and family group ranks. There are at least the following two problems seen in Search and Browse dialogues caused by this difference.

Problem 1: Search by Prefix Matching and Browse search do not work using zoological section names. Easily seen when entering section name Homoloida character by character in Browse dialogue. The dialogue 'finds' the section only after the last character of the name has been entered.

Problem 2: Balancing of the classification tree (adding "Not assigned" placeholders) gets confused by zoological sections. For example, resulting tree around Homoloida looks like nonsense:

infraorder: Brachyura Latreille, 1802
    family: †Montemagrechiridae Klompmaker, Portell & van der Meij, 2016
    family: Not assigned
        section: Homoloida Karasawa, Schweitzer & Feldmann, 2011
            superfamily: Homoloidea De Haan, 1839
                family: Homolidae De Haan, 1839

**Comment by yroskov** [comment]
@mdoering, could you please advise on how to handle the problem.
(We had the "section problem" before https://github.com/CatalogueOfLife/testing/issues/141)

**Comment by mdoering** [comment]
[Homolidae](https://www.checklistbank.org/dataset/272972/taxon/5761386d-9d27-423a-9082-8ee1d62fef0e) has a correct classification:
unranked: [Biota](https://www.checklistbank.org/dataset/272972/taxon/5T6MX) >kingdom: [Animalia](https://www.checklistbank.org/dataset/272972/taxon/N) >phylum: [Arthropoda](https://www.checklistbank.org/dataset/272972/taxon/RT) >class: [Malacostraca](https://www.checklistbank.org/dataset/272972/taxon/MC) >order: [Decapoda](https://www.checklistbank.org/dataset/272972/taxon/33N) >suborder: [Pleocyemata](https://www.checklistbank.org/dataset/272972/taxon/7NFJ8) >infraorder: [Brachyura Latreille, 1802](https://www.checklistbank.org/dataset/272972/taxon/c39ee8d3-db91-48aa-b807-5cc6ac1630ed) >section: [Homoloida Karasawa, Schweitzer & Feldmann, 2011](https://www.checklistbank.org/dataset/272972/taxon/e5caa9a9-aac7-421a-b91b-c3908308a7ce) >superfamily: [Homoloidea De Haan, 1839](https://www.checklistbank.org/dataset/272972/taxon/63f30e30-3817-4265-a9f6-9b8edf17defa) >family: [Homolidae De Haan, 1839](https://www.checklistbank.org/dataset/272972/classification?taxonKey=5761386d-9d27-423a-9082-8ee1d62fef0e)


... the problem seems to be just the tree browsing with placeholders.

I think the problem is the one extinct family [Montemagrechiridae](https://www.checklistbank.org/dataset/272972/taxon/bd4bf234-4509-44b5-9e15-2b469e33108e) which is not organised in any section. This causes the family placeholder to be created above the sections. Any chance to move that family under some section?
This causes

**Comment by mdoering** [comment]
The only real solution would be to create separate rank entries for zoology and botany - sth which I had considered several times before: https://github.com/gbif/name-parser/issues/96

**Comment by aoern** [comment]
I think you are right, @mdoering.
I have done that (separate rank entries for zoology and botany) in my 'private' copy of CoL database, and it works fine.

**Comment by mdoering** [comment]
Do you have encountered zoological `series` in the data? That seems harder to tackle in zoology as it seems to be a rank used in different places depending on the zoological group - at least according to [Wikipedia](https://en.wikipedia.org/wiki/Taxonomic_rank#All_ranks): 
<img width="762" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/7e340efc-98e2-4775-a4b9-e4753bf56f82">

**Comment by mdoering** [comment]
It is a lot of work to add new ranks. We will have to reindex all datasets. It would be good to do as much as we can in one go.
@dhobern ever encountered a Lepidoptera series?

**Comment by yroskov** [comment]
>But why not in CoL?

Because CoL data providers for plants do not use series.

**Comment by mdoering** [comment]
NOMEN also does not contain any zoological series rank.
Maybe we do not have to worry about it

**Comment by aoern** [comment]
Ok. Let's forget about series.

**Comment by dhobern** [comment]
The ranks in use in Lepidoptera (aside from some unranked higher clades) are:

- superfamily
- family
- subfamily
- tribe
- subtribe
- genus
- subgenus
- species
- subspecies

Older names were published as varieties and forms (and races) but only these ranks appear in modern taxonomic works. In some large genera, species groups are given names and referred to over time, but these seem to be an administrative solution rather than final rank choices.

COL/GLI is patchy in the detail it includes between family and genus. I generally try to include subfamily and tribe where I can - much of the literature ignores subtribes so it can be hard to be consistent if you try to include those.

**Comment by mdoering** [comment]
deployed to prod and all sections with code=zoological have been changed to the new section_zoology rank:

<img width="871" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/3404c229-f63c-4120-a44f-6954e9811289">

The importer & name parser pick the section based on the code they are aware of, defaulting to the botanical section if unknown.

**Comment by mdoering** [comment]
https://www.catalogueoflife.org/data/browse?taxonKey=63f30e30-3817-4265-a9f6-9b8edf17defa
