### ISSUE TITLE
25.000+ self-synonymizes taxa

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#598]
There are over 25.000 self-synonymized taxa in Nov-2023 edition, mostly in Systema Dipterorum, GLI and 3i Auchenorrhynca.
In Oct-2023 there were only <300 such cases.

In Systema Dipterorum they are caused by removal of subgenera.
For example, in Oct-2023 edition we had
accepted Acrocera (Acrocerina) altaica  Pleske, 1930
synonym Acrocera altaica  Pleske,1930
and in Nov-2023
accepted Acrocera altaica  Pleske,1930
synonym Acrocera altaica  Pleske,1930

In 3i Auchenorrhyncha and GLI self-synonyms are caused by removed square brackets around the generic names.
For example, in Oct-2023:
prov. accepted [Cicada] melanaria	Germar, 1830
synonym Cicada melanaria  Germar, 1830
and in Nov-2023:
prov. accepted Cicada melanaria  Germar, 1830
synonym Cicada melanaria  Germar, 1830

**Comment by yroskov** [comment]
Well, changing the rules during the game (e.g. handling subgenera in CLB) does not contribute to a quality of the product. I hope that self-synonymized names will be gradually eliminated with new updates of GSDs.

@gdower & @mdoering, could you please have a talk whether adjustment in Geoff's scripts needed or not.

**Comment by yroskov** [comment]
> For example, in Oct-2023 edition we had
> accepted Acrocera (Acrocerina) altaica Pleske, 1930
>synonym Acrocera altaica Pleske,1930

= This is correct presentation! 


> and in Nov-2023
> accepted Acrocera altaica Pleske,1930
> synonym Acrocera altaica Pleske,1930

= This is incorrect presentation, because subgenus removed from the name.

**Comment by yroskov** [comment]
> In 3i Auchenorrhyncha and GLI self-synonyms are caused by removed square brackets around the generic names.

If square brackets removed from unaccepted names by the CLB software, it (1) create a problem to flag combinations as provisionally accepted, and (2) create confusion with "self-synonymized names".

My editor's opinion, CoL should display names with genera in square brackets as they supplied by GSDs (repeated many times already).

**Comment by mdoering** [comment]
It is a painful, long ongoing discussion if we should include all kind of string variations or just consider truly different parsed names. I cannot see advantages of having redundant names with minor spelling or subgenus differences. I think COL would be much cleaner if it had only one copy of a name. Question is then what makes a name unique, a fundamental discussion I raised from the start of the project: https://github.com/CatalogueOfLife/general/issues/35

A major part of the problem is that we deal with names as a parsed instances _in addition_ to keep it as 2 simple strings (scientificName & authorship). That easily causes conflicts and one has to have clear rules what takes precedence. Do we rebuild the name string from the parsed content or do we stick to the name string no matter what? The parsed name is essential for name matching and working with names, e.g. during assembly syncs when we want to make sure a (sub) genus exists for a lone species. This is why I am leaning towards the parsed name being the ultimate source of truth and the scientificName is the label we reconstruct. That has problems in cases when the name parsing goes wrong. Having genus names with square brackets is another troublesome issue as it prevents from matching and generating implicit names correctly. I have been advocating for a long time that we can use these brackets in the "label" of the name when we reconstruct the scientificName, but not in the parsed name. We'd need a flag to indicate that the genus is considered the wrong placement. Which is also problematic as it is a taxonomic opinion and not a nomenclatural property and thus does not belong on a Name instance but instead should rather be part of the Taxon label. @dhobern @yroskov @olafbanki We really need to agree on a solution and should discuss the doubtful placement of genera again on some issue if we haven't got one open already.

**Comment by mdoering** [comment]
We have a convention in ColDP / CLB how to deal with uncertain genus placement:
https://github.com/CatalogueOfLife/coldp/blob/master/README.md#species-with-an-uncertain-genus

Here are related issues to the uncertain/doubtful genus placement:

 - https://github.com/CatalogueOfLife/coldp/issues/45
 - https://github.com/CatalogueOfLife/data/issues/382
 - https://github.com/CatalogueOfLife/data/issues/469
 - https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-1045199243
 - https://github.com/CatalogueOfLife/testing/issues/224#issuecomment-1515518918

**Comment by gdower** [comment]
I think we should take greater advantage of the verbatim data model. I understand the importance of parsing the name to make it machine readable, but in reconstructing the name as a label, the original data in the string (like non-standardized taxonomist comments) are likely lost. Being able to view and search on the verbatim name and verbatim authorship provided by the data source could immediately help clarify the source of duplicates and other problems. We already have the verbatim data stored (although I think it is no longer included with releases). It seems like it would be worthwhile adding two verbatim columns so that the parsed name can be visually compared below the parsed name (possibly hidden in the COL portal until you click a view original data button). Then we'd get the best of both worlds with the machine readable version and the needed context to interpret common data problems. It's also important to have that verbatim data quickly viewable in the ChecklistBank editorial tools, otherwise editors do not have the context needed to efficiently make editorial decisions without having to navigate to the verbatim data page in the source dataset which takes up a lot of time. I think we need a similar approach for name statuses, with the original name status recorded and presented side-by-side with the unified/simplified name status, because there's often confusion over the simplified name status.

**Comment by mdoering** [comment]
@yroskov the Diptera sector does not include subgenera as a rank to be synced:
<img width="1286" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/3dfab766-b080-4a32-a3a2-15aa1932fc2e">

It is also lacking the zoological code, but that probably doesn't matter as the dataset itself has it configured for all imports.

**Comment by mdoering** [comment]
The [sector](https://api.checklistbank.org/dataset/3/sector/1386) was last modified in June on 2023-06-12T18:47:56.450251, since then the only syncs were at the end of October and in November. That means any changed done in the sector would have only been picked up in the November release, the data since June was stale.

I don't think this is a software change/problem, but simply aa changed sector configuration that only now has been seen/applied.

**Comment by yroskov** [comment]
> that means any changed done in the sector would have only been picked up in the November release, the data since June was stale.

I never touch Systema Dipterorum sector configuration, neither in October-November, nor earlier (I only synced it). @gdower, did you?

**Comment by mdoering** [comment]
... it says modified by user [102](https://api.checklistbank.org/user/102) which is you ;)

**Comment by yroskov** [comment]
Very often CLB claims that I did some imports and metadata, which I never touched.

**Comment by yroskov** [comment]
@mdoering, is there a way to retrieve IP addresses for "user 102" in CLB?

**Comment by yroskov** [comment]
@mdoering, you are right, I did block subgenera in SD. Thanks to @gdower. He did find my comment in June _Split subgenera - failed to resolve = the sector synced without rank subgenus_ https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-1587804958

**Comment by mdoering** [comment]
If split subgenera cannot be resolved personally I think it is fair to ignore subgenera and have just Diptera species names without them. That then produces the duplicates and self synonyms @aoern originally complained about. With the new merge sectors we use for the extended list this would not happen and only one instance of the same name would be added - accepted preferred over synonym. Maybe that is sth to look into for Diptera? I will setup a quick test project and merge the names into that so you can compare results.

**Comment by mdoering** [comment]
sync is done: <img width="1885" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/56b26092-f67f-40e4-8a11-80d6b1575587">

**Comment by yroskov** [comment]
@mdoering, I have no access to the project  https://www.checklistbank.org/catalogue/280756

![image](https://github.com/CatalogueOfLife/data/assets/28574252/11a7a985-837b-4ab8-bf29-ec5af7df9953)

**Comment by yroskov** [comment]
Yes, I have access to https://www.checklistbank.org/catalogue/280756/names. Thanks!
