### ISSUE TITLE
Family misspelling

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#639]
<img width="400" alt="image" src="https://github.com/CatalogueOfLife/data/assets/327505/c0b28d94-50c7-4582-b7e9-89f8a3ce05d8">

**Comment by mdoering** [comment]
Merge these names in the extended release. Either via the patch dataset or an editorial UPDATE decision with the keepOriginalName flag set.

**Comment by mdoering** [comment]
@camiplata maybe you can add a decision for this one too today

**Comment by DaveNicolson** [comment]
Out of curiosity, what is the "misspelled" name in the image? I ask because the last 2 names in the image are separate names based on separate genera, they are not the same family...

**Comment by TonyRees** [comment]
You are correct David, thanks for that... also as reflected in the present version of WoRMS. Actually I had them confused in IRMNG, with the earlier one as a supposed misspelling of the later one (which clearly does not make sense), so have (just now) separated them again although that correction will not make it through to GBIF until the next stable release of IRMNG. In any case GBIF most likely would not have adopted the IRMNG treatment since it does not use that for Polychaetes, hopefully!
