### ISSUE TITLE
Taxon with UUID instead of Latin29-style identifier in NamesUsage.tsv

### ISSUE THREAD

**Issue by rdmpage** [CatalogueOfLife/data#640]
Hope this is the right place for this issue, it wasn't clear to me where to post it.

I have downloaded the CoL data dump (the file has UUID da78bfe9-22bb-4f19-8517-de46649ed9a0) and I am trying to load the file `NameUsage.tsv` into a local database. I am translating the CoL taxon ids from Latin29 (e.g., `8M8L`) into integers (e.g., `160821`) to make queries faster.

When doing this I hit instances where a taxon id is NOT a Latin29 number but, for example, a UUID. In the current dump, the genus Rak [76VB](https://www.catalogueoflife.org/data/taxon/76VB) has as its parent `3bf368f7-754c-4ac1-a1fc-a24be6162bea` (which is an example of `Not assigned`). 

Is this intended? Do `Not assigned` taxa always have UUIDs? I assume not.

Investigating further, in the portal, if I mouse over the "not assigned" taxon that includes : [Lahmiales](https://www.catalogueoflife.org/data/taxon/3F3) the parent link is `https://www.catalogueoflife.org/data/taxon/SM--incertae-sedis--CLASS`, but in the `NamesUsage.tsv` dump the parent is simply `SM`
![Screenshot 2024-04-17 at 17 46 45](https://github.com/CatalogueOfLife/data/assets/83306/ae780766-02be-4bb6-88fb-364732c33333)

**Comment by yroskov** [comment]
@mdoering, it's for you.

**Comment by rdmpage** [comment]
There seem to be three UUIDs in the data dump:
```
3bf368f7-754c-4ac1-a1fc-a24be6162bea
3ad0e30f-8260-4cb4-a710-a3d0182be96a
b8911045-62e8-421f-8d3b-0f0aee52095a
```

**Comment by mdoering** [comment]
Hi Rod, this is (unfortunately) expected and there are 2 different things involved here.
For some very few names which we don't expect to be part of the COL and cannot be stable the UUIDs indeed do exist.
This is in the current march edition true for [1 placeholder and 2 no names](https://www.checklistbank.org/dataset/292011/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&limit=50&nameType=placeholder&nameType=no%20name&offset=0&sortBy=taxonomic) only:

(the other "no names" seem to be flagged because of their non ascii characters in the name - my guess)

```
                  id                  |  status  | parent_id |    type     |    rank    |              scientific_name               | authorship 
--------------------------------------+----------+-----------+-------------+------------+--------------------------------------------+------------
 3bf368f7-754c-4ac1-a1fc-a24be6162bea | ACCEPTED | BRGBD     | PLACEHOLDER | FAMILY     | Not assigned                               | 
 b8911045-62e8-421f-8d3b-0f0aee52095a | SYNONYM  | 9RH3B     | NO_NAME     | SUBSPECIES | [GENUS NOT SPECIFIED] lunatum inconjunctum | Pic, 1920
 3ad0e30f-8260-4cb4-a710-a3d0182be96a | SYNONYM  | 9RH3C     | NO_NAME     | SUBSPECIES | [GENUS NOT SPECIFIED] lunatum rufithorax   | Pic, 1920
```

I guess you can safely skip these names - easily at least the synonyms, the accepted might be a parent of some others and you need to rewire them.

The "identifier" you took from the frontend isn't a real one. It is a dynamic one that identifies virtual placeholders that we create on the fly to group children of that have a lower rank than the highest ranked children. E.g. when a family contains 5 genera and 2 species the species will be grouped under a "Not assigned" tree node which does not exist in the database and is just for better visualisation. You can actually turn this virtual grouping feature on and off in checklistbank, see `Show placeholder ranks`: https://www.checklistbank.org/dataset/292011/classification

So `SM--incertae-sedis--CLASS` actually means the placeholder under taxon SM which groups children below the class level and is considered to be shown as a class. This is done in the Tree API. The children of SM have mixed ranks with class being the highest one:
https://api.checklistbank.org/dataset/292011/tree/SM/children

You can ask the API to group the non class names and return a virtual placeholder / incertae sedis node instead:
https://api.checklistbank.org/dataset/292011/tree/SM/children?insertPlaceholder=true

**Comment by rdmpage** [comment]
@mdoering Many thanks for the detailed explanation, I'll tweak my code to handle the UUIDs by mapping these to integers that are larger than those expected for the existing CoL ids.
