### ISSUE TITLE
GLI: Global Lepidoptera Index - Should Papilio circe be a synonym of Loweia tityrus (Poda, 1761)?

### ISSUE THREAD

**Issue by ManonGros** [CatalogueOfLife/data#642]
**Describe the problem**:

This a question which follows this GitHub issue originally logged on the GBIF Portal feedback: https://github.com/gbif/portal-feedback/issues/4493

According to [TAXREF](https://www.gbif.org/dataset/0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6), _Brintesia circe_ is a synonym of Papilio circe Fabricius, 1775: https://www.gbif.org/species/222214176
According to the Global Lepidoptera Index via the Catalogue of Life, Papilio circe (Denis & Schiffermüller) 1776 is a synonym of Loweia tityrus (Poda, 1761): https://www.gbif.org/species/200608893 and https://www.catalogueoflife.org/data/taxon/3W8HV

But according to the GBIF user who logged the original feedback message,  _Brintesia circe_  and _Loweia tityrus_ shouldn't be synonyms.

I don't find _Brintesia circe_ in the Catalogue of Life. I suspect that Papilio circe and Loweia tityrus shouldn't be synonym. Do you know if that's the case?

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/3W8HV

**Literature references**:
None

**Comment by yroskov** [comment]
For attention of @dhobern

**Comment by dhobern** [comment]
The correct name was present, but hidden as Satyrus circe without an original combination. Both Fabricius and D&S used the name Papilio circe for different butterflies in a two-year period.

I have moved Satyrus circe to become Brintesia circe and include Papilio circe (Fabricius) and Satyrus circe as synonyms.

I have moved Lowesia tityrus to become Lycaena satyrus since that is the preferred combination and include Papilio circe (D&S) as a synonym.

These fixes should be uploaded to ChecklistBank  in the next few days. They will then make it into COL in the next month or so.

Butterflies are a complete mess in COL - I am working hard to find complete and better curated data as a starting-point.
