### ISSUE TITLE
Authorship errors in Bacteria

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#649]
The 15 bacterial names listed below have two extra characters ". " in front of their authorship string. These seem to be artefacts from removing 'corrig.' phrases from the string. For example, the Taxon Page of Alcanivoracaceae displays the authorship string as
"corrig. . Golyshin et al., 2005".

Alcanivoracaceae                  . Golyshin et al., 2005
Desulfarculales                      . Kuever et al., 2006
Desulfonatronaceae              . Kuever et al., 2006
Desulfuromonadaceae          . Kuever et al., 2006
Desulfuromonadales             . Kuever et al., 2006
Firmicutes	                      . Gibbons & Murray, 1978
Halanaerobiaceae	              . Oren et al., 1984
Halanaerobiales                    . Rainey & Zhilina, 1995
Ktedonobacteraceae             . Cavaletti et al., 2007
Ktedonobacterales                . Cavaletti et al., 2007
Ktedonobacteria                    . Cavaletti et al., 2007
Rhizobium selenitireducens  . Hunter et al., 2008
Saccharothrix variisporea      . (ex Tomita et al., 1977) Kim et al., 2011
Sorangiineae                         . Reichenbach, 2007
Thioalkalivibrio halophilus    . Banciu et al., 2005

**Comment by yroskov** [comment]
@gdower, I guess, it's for you to resolve.

Here is an example of what's happened:

ITIS master view: Alcanivoracaceae  corrig. Golyshin et al., 2005
https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=956322#null

CLB, ITIS verbatim: Alcanivoracaceae corrig. . Golyshin et al., 2005
https://www.checklistbank.org/dataset/2144/taxon/956322

![image](https://github.com/CatalogueOfLife/data/assets/28574252/2d281a61-b5b8-49f8-bdee-637a67351e09)

**Comment by mdoering** [comment]
The verbatim data looks fine to me. The importer just fails to remove the dot in corrig. if its given as a distinct authorship.
Fixed in code just now. All these authorship issues root in the fact that we try to use the given authorship instead of rebuilding it from the parsed data. When we reuse the exact authorship we need to remove the parts which we have extracted (sic, corrig, sensu, non) and placed into other fields, so they are not duplicated in the final "label". But because parsing and removing are different pieces of code and there is the option of supplying the authorship as part of the name or separately, this makes it rather complex and easy to introduce some "bugs". 

Hope we're getting there now
