### ISSUE TITLE
Use ZooKeys checklist "An updated checklist of the European Butterflies (Lepidoptera, Papilionoidea)"

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#704]
https://zookeys.pensoft.net/article/28712/

Only contains 496 species, but it is from 2018 and will contain all current European species.
We should add it to the XRelease in probably rather high prio - too bad we cannot override the outdated base resources.

**Comment by mdoering** [comment]
taxonomy extracted here: https://www.checklistbank.org/dataset/303328/about
references could also be added if useful

**Comment by mdoering** [comment]
data managed in https://github.com/CatalogueOfLife/data-euro-leps

**Comment by larspett** [comment]
@mdoering Has this gone live? Because the scientific names that we currently get for the Swedish (and European) butterflies in GBIF are not aligned with the Wiemers et al paper referred to here. I am quite sure they used to be, but they are not now. Anyway, there are numerous genus names that I find now as names for Swedish species which do not conform to the Wiemers et al paper, which we and most butterfly people in Europe use as the current standard. What is worse is that there have surfaced synonyms that are wrong and that haven't been supplied by us here in Lund @larspett & @mathieuLU (maybe worth an issue of its own but since this issue is active & relevant, I post the problem here) 

- If you look at one record from our sebms dataset https://www.gbif.org/occurrence/2562558295
- That links to both: https://www.gbif.org/species/1929443
- and https://www.gbif.org/species/1929270

L. dispar has never been a synonym of L. hippothoe and the issue is quite urgent as L. dispar is listed in the EU Habitats Directive and is just due to be evaluated.

I found another similar thing with one more species in the sebms data:

- https://www.gbif.org/occurrence/3003686473 (Limenitis reducta does not occur in northern Europe) 
- and the distributions of L. camilla (which occurs here) and L. reducta look like they have been mixed, at least partially https://www.gbif.org/species/8001799

**Comment by mdoering** [comment]
@larspett GBIF does not yet use the Catalogue of Life as its taxonomy. The issue here is to add it to COL.
The GBIF Backbone Taxonomy will not be updated again and remains as it was created in August 2023.

We will start indexing all GBIF also against the extended release of COL in the near future though, so you will then be able to view GBIF data against the latest monthly COL release using Wiemers. The butterfly taxonomy in COL will still not exactly follow Wiemers as it is based primarily on [GLI](https://www.catalogueoflife.org/data/dataset/55434). Only names & combinations missing will be added.

**Comment by larspett** [comment]
Ok thanks for the quick clarification! Should I raise this as a separate issue then? Those two mixups that I listed are quite critical

**Comment by mdoering** [comment]
For GBIF occurrence interpretation it might be good to deal with the problem elsewhere, but I don't see what GBIF could do to fix this when the taxonomy is immutable.

I have looked at GLI and Lycaena hippothoe is treated there as a [subspecies](https://www.checklistbank.org/dataset/55434/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Lycaena%20hippothoe&sortBy=taxonomic) of [Lycaena dispar](https://www.checklistbank.org/dataset/55434/taxon/423828)

Maybe @dhobern can have a second look and apply some corrections if needed?

**Comment by mdoering** [comment]
I am closing this issue though, as the original problem of adding the Wiemer list to the COL XReleases has been done
