### ISSUE TITLE
Curculionidae: Sitones & Sitona overlap

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/data#706]
Within the Curculionidae, [Sitones Schoenherr, C.J., 1840](https://www.checklistbank.org/dataset/303642/taxon/8HR5T) from WTaxa and [Sitona Germar, 1817](https://www.checklistbank.org/dataset/1166/taxon/728706) from World Entiminae Database which has _Sitones_ Schoenherr, 1840 as a synonym, overlap a lot with redundant species.

**Comment by yroskov** [comment]
Fixed 2024-10-07

**Comment by dhobern** [comment]
@yroskov Could you also check other genera in these two datasets - there was a comment, I think from Tony Rees, that there were quite a few weevil genera that were misplaced in GBIF. I wonder if this example is just one of a more general set of missed identities when merging Entiminae. Since the WTaxa list did not include subfamilies, detecting and excluding the correct genera when Entiminae were added could have been rather messy.

**Comment by yroskov** [comment]
@dhobern, I blocked a lot of WTaxa genera overlapped with Entiminae at the stage of Entiminae entry in the CoL (i.e. all overlaps that **I was able to identify** were resolved). 

I'll ask Entiminae authors for help.

**Comment by yroskov** [comment]
@dhobern, before I turn to Nikolai Yunakov for further assistance, could you please let me know what is the outcome of his request to join the Taxonomy Group as a Coleoptera expert?
