### ISSUE TITLE
Regression for Myosotis L.

### ISSUE THREAD

**Issue by ahahn-gbif** [CatalogueOfLife/data#727]
This jump from "Myosotis" to "Plantae" seems large

```
{
  "count": 25611,
  "verbatim_taxonID": "null",
  "verbatim_taxonConceptID": "null",
  "verbatim_scientificNameID": "null",
  "verbatim_kingdom": "Plantae",
  "verbatim_phylum": "null",
  "verbatim_class": "null",
  "verbatim_order": "null",
  "verbatim_family": "null",
  "verbatim_genus": "null",
  "verbatim_species": "null",
  "verbatim_infra": "null",
  "verbatim_rank": "null",
  "verbatim_verbatimRank": "null",
  "verbatim_scientificName": "Myosotis scorpioides agg.",
  "verbatim_generic": "null",
  "verbatim_author": "null",
  "current_kingdom": "Plantae",
  "current_phylum": "Tracheophyta",
  "current_class": "Magnoliopsida",
  "current_order": "Boraginales",
  "current_family": "Boraginaceae",
  "current_genus": "Myosotis",
  "current_subGenus": "null",
  "current_species": "null",
  "current_scientificName": "Myosotis L.",
  "current_acceptedScientificName": "Myosotis L.",
  "proposed_kingdom": "Plantae",
  "proposed_phylum": "null",
  "proposed_class": "null",
  "proposed_order": "null",
  "proposed_family": "null",
  "proposed_genus": "null",
  "proposed_subGenus": "null",
  "proposed_species": "null",
  "proposed_scientificName": "Plantae",
  "proposed_acceptedScientificName": "Plantae",
  "debug_url": "http://backbonebuild-vh.gbif.org:9101/v2/species/match?&kingdom=Plantae&scientificName=Myosotis scorpioides agg.&strict=false",
  "_key": 18253,
  "changes": {
    "phylum": true,
    "class": true,
    "order": true,
    "family": true,
    "genus": true,
    "scientificName": true,
    "acceptedScientificName": true
  },
  "reviewed": false
}
```

**Comment by camiplata** [comment]
Posible matching issue, [the species name does exist ](https://www.checklistbank.org/dataset/304862/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Myosotis%20scorpioides&type=EXACT)(although not the species aggregate name), maybe a problem cause by having to potential matches?

**Comment by mdoering** [comment]
We got 3 Myosotis genera, one being a wrong duplicate with very little classification:
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/4204e842-9794-418b-9d38-c1bd6c083d3a">

As both the accepted homonym genera and the input classification only agrees on Plantae, that's what we get.
So its not matching but a badly merged genus `Myosotis Linnaeus, 1753` from PBDB.

Interestingly the species [Myosotis scorpioides](https://www.checklistbank.org/dataset/304862/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=%20Myosotis%20scorpioides&rank=species&sortBy=taxonomic) even exists, but I think the matching goes up to genus level because of the aggregate qualifier and then hits the homonym problem.

**Comment by mdoering** [comment]
@camiplata can you please block the genus from PBDB? I will try to also solve this programmatically, but not sure whats going on so far

**Comment by mdoering** [comment]
only 1 accepted Myosotis left in 8th Nov edition:
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/16424b3b-3dcd-4fd4-9844-2fa84342dfcf">

And no impact tool problems for the aggregate above any longer!
